server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/coupon?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: zxy@AHU123
  redis:
    host: localhost
dubbo:
  registry:
    address: localhost:2181
  protocol:
    port: 20880